sudo: false
language: scala
jdk: openjdk8
env:
  global:
  # PGP_PASSPHRASE=
  - secure: OYFj6Bmt0ezWAqQV5VoURXhv8HBvOq6N2fejyDJXSZIOfTJ8LNDrly4hjXphA6U6rg3nourbSBMj4Ua2S3ulffHrNADkDCRkcLYjEyBgD0ru2MGsqi1XFPeDJooBuYNkEbEfxIIq7GLMl/o6LSkpSJiEP0EfZoqCJ0PgvpXe8Oo=
  # BINTRAY_USER=
  - secure: BIzpjpH6bdCFvueMzQ/yFNv0VGyZrMtC1ChGVtvk4KojRh0wuY6cKYm1z6sC2wkY/4doqvFg/a11ngaAt47vP3Yt6mI4DN3ZM5nW22v5ZTiR3yMI2sXoQ6XQwF13ESQLywjtXM6BA8emDP4VmnY5nPZ/KZKWIoI6JbQ0Hc1ScVE=
  # BINTRAY_PASS
  - secure: SM0FjGDTftGTKv/UnVkMMOXj43tCPurTkSykW5nyscTRjbQrtMCa1iMddQfwerx47qYM9c5jUDpOkuPWgAzNVHeD/sQAgQj6PIlTgCx8AbtAWtSkujI+SuytnXZa5av9n4YIPg/7EvcrAKEyy8EVzhzhnkvit6rTlOCmYMVNAo8=
before_script:
- gpg --import test-key.gpg
script:
- sbt "++${TRAVIS_SCALA_VERSION}" test scripted
matrix:
  include:
  - scala: 2.10.7
  - scala: 2.12.10
after_success:
  - .travis/publish.sh
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
- rm -f $HOME/.ivy2/.sbt.ivy.lock
cache:
  directories:
  - "$HOME/.cache/coursier"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
