sudo: false
language: scala

jdk: openjdk8

before_script:
  - gpg --import test-key.gpg

script:
  - sbt "++${TRAVIS_SCALA_VERSION}" test scripted
matrix:
  include:
  - scala: 2.10.7
  - scala: 2.12.10
