sudo: false
language: scala

before_script:
  - gpg --import test-key.gpg

script:
  - sbt "++${TRAVIS_SCALA_VERSION}" test scripted
matrix:
  include:
  - jdk: openjdk7
    scala: 2.10.6
  - jdk: oraclejdk8
    scala: 2.12.3
  - jdk: oraclejdk10
    scala: 2.12.6
